### PR TITLE
adding privileged flag to docker containers

### PR DESCRIPTION
**Pull request by jkrshnmenon**

### CODE REVIEW

**Comment by rhelmot** [comment]
This is not complete - the kubernetes container manager does not actually do anything with the privileged flag. However, I am fine with leaving this incomplete for another day.

**Comment by jkrshnmenon** [comment]
executor can now set the privileged flag for kubernetes pods

**Comment by rhelmot** [comment]
Deal with the failing lint passes and I'll hit merge

**Comment by rhelmot** [comment]
wtf codecov shut up

**Comment by jkrshnmenon** [comment]
Alright, linting succeeds now

**Pull request merged**
